name: fireflutter_in_app_purchase
description: FireFlutter in-app-purchase package. This package is a submodule of fireflutter.
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.24.1
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  in_app_purchase: ^0.3.4+16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
