name: fireflutter_in_app_purchase
description: FireFlutter in-app-purchase package. This package is a submodule of fireflutter.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  in_app_purchase: ^0.3.4+16

  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
